<script>
  import HeadingText from "./HeadingText.svelte";
  import ProjectCard from "./ProjectCard.svelte";
  import TopNav from "./TopNav.svelte";
  import { web3, defaultEvmStores } from 'svelte-web3';
  // import Web3Modal from "web3modal";


  let values = [
    {
      src: "/character-1.png",
      alt: "Character 1",
    },
    {
      src: "/character-2.png",
      alt: "Character 2",
    },
    {
      src: "/character-3.png",
      alt: "Character 3",
    },
    {
      src: "/character-4.png",
      alt: "Character 4",
    },
    {
      src: "/character-5.png",
      alt: "Character 5",
    },

  ];
  let team = [
    {
      src: "/vlad.png",
      alt: "Character 1",
      twitter: "https://twitter.com/vladrooman2",
      name: "VLAD ROMAN"
    },
    {
      src: "/modrogan.png",
      alt: "Character 1",
      twitter: "https://twitter.com/modroagency",
      name: "MODROGAN"
    },
    {
      src: "/stoned-monkey.png",
      alt: "Character 1",
      twitter: "https://twitter.com/StonedMonkey666",
      name: "STONEDMONKEY"
    },
    {
      src: "/profile-pic-cropped.jpg",
      alt: "Character 1",
      twitter: "https://twitter.com/dill_eth",
      name: "dill.eth"
    },
    {
      src: "/justin-cures.jpg",
      alt: "Character 1",
      twitter: "https://twitter.com/justincures",
      name: "JUSTIN CURES"
    },
    {
      src: "/rezz.png",
      alt: "Character 1",
      twitter: "https://twitter.com/rezz6969",
      name: "REZZ"
    },
  ];
</script>

<main>
  <div class="pb-24">
  <div class="main-banner">
    <TopNav/>
    <div class="flex justify-center pt-96">
      <img class="h-24" alt="KomplitApp" src="free-mint.png" />
    </div>

    <div class="flex justify-center">
      {#if !$defaultEvmStores.connected}
        <button class=" text-white font-bold py-2 px-4 rounded" on:click={defaultEvmStores.setProvider()}>
          connect wallet
        </button>
      {:else}
        <button class=" text-white font-bold py-2 px-4 rounded" on:click={defaultEvmStores.setProvider()}>
        Mint
        </button>
      {/if}
    </div>
  </div>

    <div class="description flex-grow flex-col justify-center items-center text-center mx-96 my-20">
      <h1 class="text-6xl underline text-center mb-4 text-purple-300 my-4">STORY</h1>
      <p>
      At the beginning of the 5th era, when there was still nothing, no time, no light.. the day was submerged in deep and absolute
      darkness. Then the gods met in Teotihuacán and decided to sacrifice 2 of them to create light and illuminate the world
      Tecuciztécatl, "The precious, adorned and pretentious god" and Nanahuatzin, "The bubbling and mangy god", were the chosen ones.
      Both stood next to the Teotexcalli, a fire that burned for four nights, and at the command of the other gods .. they threw
      themselves into the fire. Suddenly everything turned reddish and at that moment Nanahuatzin emerged. It was so resplendent that
      no one could look at it. Then right in the same place Tecuciztécatl appeared, and the gods noticed that it was not right that there
      were 2 suns. Then, Quetzalcóatl hit Tecuciztécatl with a rabbit, thus suppressing the glow and creating the Moon. <br/><br/>
      After a while, the gods noticed that the sun and the moon were immobile and decided to give them movement.<br/><br/>
      "Let us sacrifice ourselves and make them resuscitate with movement for our death," the gods said and all accepted, except one
      Xólotl, Quetzalcoátl's twin, refused to sacrifice himself, HE LOVED LIFE! so he decided to flee showing off his ability to transform, he
      hid between a cornfield and took the form of a corn, but it was discovered, it fled again to hide in a maguey and again it was
      discovered, it finally escaped to the water, where it took the form of an axolotl, which was the last being it could transform into
      Before dying, his impressive will to live led him to create his next descendants, the Genesis aXos, these creatures stored in the ETH
      Blockchain fight to escape the god of death who punished their ancestor and is now looking for them, that is why they seek to
      shelter in your wallet for as long as possible, to give you security, fortune and absolute fun in community. <br/><br/>
      Now it is your duty to help them create an army of aXos to defeat the god of death .. That is why they have reproduced to create
      the Generative aXos.… randomly generated by the ancestral traits, they will help us increase in number and defeat the fearsome
      Mictlantecuhtli.…. God of death.
      </p>
    </div>
    <div class="grid grid-cols-5">
      {#each values as { src, alt}}
        <div class="flex flex-col items-center">
          <img
          {src}
          {alt}
          class="w-72 h-72 mb-4 transform transition-transform hover:rotate-12"
          />
        </div>
      {/each}
    </div>

    <h1 class="text-6xl underline text-center mb-4 text-purple-300 my-4">JOURNEY</h1>
    <div class="flex">
      <div class="flex-1"></div>
      <div class="flex-1 left-journey p-10">
          <div class="bg-purple-700 mx-30 p-10 mt-10">
            <div class="flex my-10">
              <div class="flex-1 rounded text-center">
                <h1 class="bg-purple-900 text-4xl font-bold">1</h1>
              </div>
              <div class="flex-1 text-center">
                <h1 class="text-4xl font-thin">1ST STOP</h1>
              </div>
            </div>
            <div class="text-center my-20">
              <h1 class="text-2xl font-bold">3333 FREE AXOS MINTED</h1>
              <p class="text-md">CCO FULL OWNERSHIP</p>
            </div>
          </div>
          <div class="bg-purple-700 mx-30 p-10 mt-20">
            <div class="flex my-10">
              <div class="flex-1 rounded text-center">
                <h1 class="bg-purple-900 text-4xl font-bold">3</h1>
              </div>
              <div class="flex-1 text-center">
                <h1 class="text-4xl font-thin">3RD STOP</h1>
              </div>
            </div>
            <div class="text-center my-20">
              <h1 class="text-2xl font-bold">
                100 ETH TTRADED - 3 ETH giveaway 
                spread to 3 random aXos holders</h1>
            </div>
          </div>
          <div class="bg-purple-700 mx-30 p-10 mt-20">
            <div class="flex my-10">
              <div class="flex-1 rounded text-center">
                <h1 class="bg-purple-900 text-4xl font-bold">5</h1>
              </div>
              <div class="flex-1 text-center">
                <h1 class="text-4xl font-thin">5TH STOP</h1>
              </div>
            </div>
            <div class="text-center my-20">
              <h1 class="text-2xl font-bold">
                2000 ETH - ?????</h1>
            </div>
          </div>
      </div>
      <div class="flex-1 right-journey p-10">
        <div class="bg-purple-700 mx-30 p-10 mt-40">
          <div class="flex my-10">
            <div class="flex-1 rounded text-center">
              <h1 class="bg-purple-900 text-4xl font-bold">2</h1>
            </div>
            <div class="flex-1 text-center">
              <h1 class="text-4xl font-thin">2ND STOP</h1>
            </div>
          </div>
          <div class="text-center my-20">
            <h1 class="text-2xl font-bold">20 ETH TRADED - 
              small donation to AXOLOTL saving irl to start with</h1>
          </div>
        </div>
        <div class="bg-purple-700 mx-30 p-10 mt-20">
          <div class="flex my-10">
            <div class="flex-1 rounded text-center">
              <h1 class="bg-purple-900 text-4xl font-bold">4</h1>
            </div>
            <div class="flex-1 text-center">
              <h1 class="text-4xl font-thin">4TH STOP</h1>
            </div>
          </div>
          <div class="text-center my-20">
            <h1 class="text-2xl font-bold">
              800 ETH - Merch adn more surprises to come given away daily in private channel (ONLY HOLDERS)</h1>
          </div>
        </div>
      </div>
      <div class="flex-1"></div>
    </div>
    <h1 class="text-6xl underline text-center mb-4 text-purple-300 my-4">TEAM</h1>
    <div class="grid grid-cols-6">
      {#each team as { src, alt, twitter, name} }
        <div class="flex flex-col items-center">
          <a href="{twitter}">
            <img
            {src}
            {alt}
            class="w-72 h-72 mb-4 transform transition-transform hover:rotate-12"
            />
          </a>
          <div>
            <h1 class="text-2xl text-purple-600">{name}</h1>
          </div>
        </div>
      {/each}
    </div>
  </div>
</main>

<style>
  main {
    background-color: black;
    color: white;
  }

  .tooltip {
    visibility: hidden;
    position: absolute;
  }
  .has-tooltip:hover .tooltip {
    visibility: visible;
    z-index: 100;
  }

  ::-moz-selection {
    /* Code for Firefox */
    /* purple-800 */
    color: #5c21b6;
    /* purple-200 */
    background: #ddd6fe;
  }

  ::selection {
    color: #5c21b6;
    background: #ddd6fe;
  }

  button{
    background-color: #d100ec;
  }

  .main-banner{
    background-image: url("/MAIN-BACKGROUND.png");
    background-repeat: no-repeat;
    background-size: 100% auto;
    height: 1000px;
    display: block;
  }

  .left-journey {
    border-right: 2px solid indigo;
  }

  .right-journey {
    border-left: 2px solid indigo;
  }
</style>
